name: SimTypora
options:
  bundleIdPrefix: com.simtypora
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  SimTypora:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.simtypora.editor
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PRODUCT_NAME: SimTypora
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: NO
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: SimTypora
        CFBundleDisplayName: SimTypora
        CFBundleIdentifier: com.simtypora.editor
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: SimTypora
        LSMinimumSystemVersion: "13.0"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
